"""
Model Deployer - Runtime execution of optimized layout schedules.

This module applies the offline schedule generated by the scheduler to a PyTorch model,
controlling where and when tensor layout conversions happen during training/inference.
"""

from .layout_actions import LayoutAction
from .layout_module import LayoutAwareModule
from .model_deployer import apply_layout_schedule, load_schedule
from .prefetcher import CudaPrefetcher

__all__ = [
    "LayoutAction",
    "LayoutAwareModule",
    "apply_layout_schedule",
    "load_schedule",
    "CudaPrefetcher",
]

